Solido/awesome-flutter

README.md

Spotted at [FlutterDev](https://www.reddit.com/r/FlutterDev/comments/6l2edn/darthub_a_quick_and_dirty_github_client_written/). As stated by the author of the repo:
>  If you'd like to build and run this project, you'll need to create a keys.dart file and define two string constants (CLIENT_ID and CLIENT_SECRET) inside it.

Added GitHub client to Open Source Apps section

---

README.md

Hi!
First of all, thanks for including my previous stuff here!
I had this internal talk at our company, and that included a sample app on how to create [this profile details page](https://www.uplabs.com/posts/profile-ui-exploration) by Masum Parvej.
I added the link to aforementioned sample app in this PR, and also fixed the list in the Templated section. :)

Add FlutterMates to Templates section

---

README.md

We moved it from the DanTup publisher to one named Dart-Code. The old URL shows a message linking to this new one.

Update link to Dart Code

---

README.md

Hey,
I added my open source app to track cryptocurrency by using CoinMarketCap API, atm I've completed the major feature to see the first 100 cryptos but more features will arrive in the next few weeks.
The design is inspired by https://github.com/sergiandreplace/planets-flutter

Add CryptoShadow in Open Source Apps

---

README.md

A Slack OAuth library that returns a FirebaseUser upon successful login, and stores accesstoken + user data in Cloud Firestore.

Added Slack OAuth Firebase extension library

---

source.md

Add flutter_inapp_purchase plugin with the almost full feature which is derived from `react-native-iap`.

Add In App Purchase plugin.

---

README.md

Flutter Rocks now does a HTTP 301 (Moved Permanently) redirect to iirokrankka.com.
**Note**: All Flutter Rocks links will still be backwards compatible till the end of time, but this is more of a branding change.
So basically, this pull request is not needed but I thought it might make sense to update anyway.

Change Flutter Rocks to iirokrankka.com

---

source.md

Sorry about the wrong previous PR.
Unfortunately `circle_indicator` is about a year without updates, I tried it and found my self on issues like https://github.com/long1eu/circle_indicator/issues/7 I tried to PR somes fixes & features, but I came up with another package with a proper way to know the current page (`circle_indicator` does offset calculation instead of using `onPageChanged`) and you can use any other Widget with any other animation, not only growing dots.

Replace circle_indicator by page_view_indicator (on source.md)

---

source.md

Admob plugin that shows banner ads using native platform views.
All current Admob implementations for Flutter, including the official one, have limitations on size and positioning when it comes to banner ads. This plugin solves those limitations by using native platform views to display banner ads.

Add admob_flutter

---

source.md

Added https://github.com/rrousselGit/flutter_hooks to the list.
It's a new way to write widgets coming from the React world that allows an improved code reuse between widgets.
Hooks are quite litteraly the future of React components, and I'd expect them to be the same for widgets. 😄

Add flutter hooks

---

source.md

Hello,
This simple PR to add a link to the French Slack.

Add the "Flutter France" Slack

---

source.md

Adding Ozzie to the list of libraries:
https://github.com/jorgecoca/ozzie.flutter

Add Ozzie to the list of libraries used for testing

---

source.md

Adds the Flutter team's sample repo (flutter/samples) as a new item in the Open Source apps section. This could also be split up into separate entries, but I feel like that would be hogging space in the list. 😄

Adds the Flutter team's sample repo

---

README.md
source.md

Catcher is Flutter plugin which automatically catches error/exceptions and handle them. Catcher offers mutliple way to handle errors. Catcher is heavily inspired from ACRA.

Added Catcher

---

source.md

The repository was moved to an organization.

Change URL for Golang desktop embedder

---

source.md

A Flutter repo with a ready-to-go architecture containing flavors, bloc, device settings, json serialization and connectivity. 
I'm also adding a link to the Brazilian's medium publication and twitter.

Adding Flutter ready_to_go project. Twitter and medium from Brazil

---

source.md

The base urls updated, so corrected the links to https://pub.dev and https://flutter.dev/
**Yes**

Updated references to pub.dev and  flutter.dev

---

source.md

A dart plugin uses on code generation for internationalization to generate darts required by [Intl](https://github.com/dart-lang/intl). This plugin provides another way for code generation which is 
more simple compared with [Intl_translation](https://github.com/dart-lang/intl_translation).

A dart plugin use on code generation for internationalization

---

source.md

This plugin supports Banner Ads, Interstitial Ads, Rewarded Video Ads, In stream Video Ads and Native Ads.

Add facebook_audience_network

---

source.md

Square In-App Payments is awesome because it's free to use the SDK, it has beautiful Flutter card animations, it was announced at the Flutter Live event made Google's top 5 highlights list, and it's backed by Square, a payment platform that has processed billions of transactions.
This [Boring Show episode](https://youtu.be/_necENw9CUs) shows how to add this plugin to Flutter's shopping cart demo app or this video is [a shorter tutorial](https://youtu.be/HFAyy_AH0No).

Add Square In-App Payments SDK

---

source.md

Highly configurable sticky headers package with ability to use inside scroll with positive and negative direction infinite list.
It fixes this kind of issues https://i.ibb.co/ZLJvwsG/sticky-jump.gif that I got in all packages with sticky headers implementation.
In addition to ability use it in straightforward way (see [docs](https://github.com/TatsuUkraine/flutter_sticky_infinite_list#available-configuration)) this package exposes classes that can be extended before it's [usage](https://github.com/TatsuUkraine/flutter_sticky_infinite_list#available-for-override)
[Example project](https://github.com/TatsuUkraine/flutter_sticky_infinite_list_example)

Add Sticky Infinite List package link

---

source.md

A flutter package which makes it easier to display the difference between two images.
Pub : https://pub.dev/packages/before_after

Add Before After widget package

---

source.md

I've added links to the Flutter community on Hashnode.
It's on the official list of Flutter communities too - https://flutter.dev/community

adding Flutter community from Hashnode

---

source.md

[snap](https://github.com/aliyigitbireroglu/flutter-snap) can be used for various purposes such as having snappable floating buttons on top of the UI without negatively effecting the UX or controlling the organisation of in-line elements while allowing the user to customise them to some extent as well. It is a very open-ended package and I believe it can be helpful to many Flutter coders.

Added "snap" to UI Helpers

---

source.md

This is to add details on the Sydney community. Created a section for Australia and put the links there. There are communities in other states too but I don't have the details on hand. GDG Sydney is listed as there isn't a Flutter Sydney meetup group and meetups involving Flutter are held within the GDG Sydney meetup group
Note that I just realised that when I fixed the description of my plugin in https://github.com/Solido/awesome-flutter/pull/515 that it turns out edited the readme. This PR now correctly updates the source.md file. Apologies for that and hope that it doesn't cause much of an inconvenience...

Add details of Sydney community and fix description of AppAuth plugin in source.md

---

source.md

Added the flutter_translate package to Internationalization (new category).
Repository: https://github.com/bratan/flutter_translate
Package: https://pub.dev/packages/flutter_translate
Thanks

Add Flutter Translate to Internationalization

---

README.md

- Reference to Youtube channel does not exist
- YouTube channel page reads "This channel does not exist"
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? 
</a>
``` 
</a>
```

Removing reference to [Fluttery] (the youtube channel under Videos header)

---

source.md

I am the main author of `amap_base_flutter` plugin and deprecated this plugin last year, I recommend to use my new amap plugin `amap_map_fluttify` to embedding amap widget to their flutter app. This new amap plugin base on `Fluttify` engine, a dart bindings generator for native SDK.

Change `amap_base_flutter` to `amap_map_fluttify`.

---

source.md

Added IDE plugin for VS Code and IntelliJ / Android Studio that makes i18n easier for Flutter development.
Plugin for VS Code: https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl
Plugin for IntelliJ / Android Studio: https://plugins.jetbrains.com/plugin/13666-flutter-intl

Add flutter intl plugin to VSCode and IntelliJ categories

---

source.md

**Note**: Not sure if it was an appropriate place in source.md, let me know if you want me to move it under another section
Dart command tool to generate Dart class and `.env` files with keys and params from command.
Allows to configure set of fields, provided in `environment_config.yaml` or in `package.yaml`.
Command can be executed for any Flutter application from terminal like
```
flutter pub run environment_config:generate --<key_name>=<key_value>
```
with `key_name`s specified in YAML file and `key_value`s for particular build environment.
Primarily created to simplify Flutter App config generation during Application builds in CodeMagic, Bitrise or any other build automation tools.

Environment specific config generator

---

live.md

You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md), right? Yes, indeed.
We are working at the moment on two weekly live streams, that includes one pair programming session on Wednesday and a Solo programming session on a Saturday. We work there together at basic Flutter Applications and talk roundabout development and answer all questions of the chat.
We are fully dedicated to it and love our work with the community. It would be an honour to be a part of the Flutter Awesome package.
(Side Note: I fixed the anchor to "Streams")
The result would look like this:
https://github.com/md-weber/awesome-flutter/blob/master/live.md
</a>

Added a live stream "FlutterExplained" to the list of Live Streams

---

source.md

</a>
``` 
</a>
```
[Link to GH repo](https://github.com/flutter/sentry)
[Link to Sentry docs](https://docs.sentry.io/platforms/flutter/)
[Link to Flutter docs for crash monitoring](https://flutter.dev/docs/cookbook/maintenance/error-reporting)

Add Sentry to the Crash monitoring section

---

source.md

</a>
``` 
</a>
```
As you asked me here https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/157
I would like to add AssetsAudioPlayer to awesome-flutter 
```
flutter:
assets:
- assets/audios/
```
```
AssetsAudioPlayer.newPlayer().open(
Audio("assets/audios/song1.mp3"),
autoPlay: true,
showNotification: true,
);
```

Add AssetsAudioPlayer

---

source.md

Added [NFC Manager](https://github.com/okadan/flutter-nfc-manager) plugin.
Why this is unique:
- It provides a pure bridge to the iOS/Android NFC API.
- It's the only one that can send vendor-specific-commands.

Add NFC Manager plugin

---

source.md

Flutter Math is a package to render TeX equations using pure Dart & Flutter. It aims to produce high-quality render result while maintaining the performance advandage of Dart & Flutter without using any WebView or Javascript. It will be an alternative to the flutter_tex package.
The project currently has 2276 SLOC of test cases. The coverage of 77% at the current stage is due to some provisioning in core structures for future development. The parser under /lib/src/parser/ has a coverage of 84%.
[Link](https://github.com/znjameswu/flutter_math)
---
**Checklist**
---

Add flutter_math

---

source.md

AuthPass is an open source password manager currently available for Android, iOS, MacOS and Linux (Windows still has some quirks). https://github.com/authpass/authpass
---
**Checklist**

Add AuthPass to apps

---

source.md

Hey @Solido 
just removing a broken link in the web demo section.
Cheers
---
**Checklist**
---
</a>
``` 
</a>
```

Removing dead link of web demo

---

source.md

[Graphic](https://github.com/entronad/graphic) is a data visualization library based on the Grammar of Graphics.
As an innovative and powerful system, the Grammar of Graphics has been widely used in data visualization, like [vega](https://vega.github.io/vega/), [chart-parts](https://microsoft.github.io/chart-parts/), [ggplot2](https://ggplot2.tidyverse.org/), etc. But it has not been introduced to the Flutter/Dart community yet.
With [Graphic](https://github.com/entronad/graphic), data analysts can create charts following their familiar grammar in Flutter Apps.
This library has got some stars on GitHub and popularity on Pub. And we have published an [article](https://medium.com/swlh/graphic-a-flutter-data-visualization-library-base-on-grammar-of-graphics-75ca751f5cae) on Medium.
So we …

Add Graphic

---

README.md
source.md

---
**Checklist**
---
</a>
``` 
</a>
```

added some state management technique and video link of resocoder

---

source.md

I felt that Flutter is still lacking some tool-support for translations, which is why I wrote `attranslate`: https://github.com/fkirc/attranslate
Note that this is not a replacement for tools like `flutter_translate`, but a complementary tool.
It runs only on the developer's machine or CI-workflows (without any impact on running apps).
---
**Checklist**
---
</a>
``` 
</a>
```

Add attranslate to Internationalization

---

source.md

Added [Zeplin Extensions - Flutter Gen](https://github.com/naver/zeplin-flutter-gen) to **Utilities** section.
The Flutter dart code generator from [zeplin](https://zeplin.io/).
---
**Checklist**

Add Zeplin Extensions - Flutter Gen

---

source.md

Add link to the russian Flutter Dev Podcast Spotify page.
https://github.com/saturov/awesome-flutter/tree/add-flutter-dev-podcast-rus#podcasts
---
**Checklist** 
---

Add russian Flutter Dev Podcast

---

source.md

Just a small typo in the project name.
https://github.com/BayesWitnesses/m2cgen
---
**Checklist**
---
</a>
``` 
</a>
```

Fix typo in m2cgen project name

---

source.md

[Dart Code Metrics](https://github.com/dart-code-checker/dart-code-metrics) is a static analysis tool that helps developers analyse and improve their code quality.
* Reports code metrics
* Provides additional rules for the Dart analyzer (and have special rules for Flutter)
* Checks for anti-patterns
* Checks unused *.dart files
---
**Checklist**

Add Dart Code Metrics

---

source.md

https://github.com/csells/go_router
go_router it's a great router package for Flutter navigation. I think that the awesome list should include it in the Navigation category.
The feature that shines the most is easy to write declarative routes. It has features like integration with Flutter Navigator 2.0, deep linking, error handling, redirection, route debugging, nested navigation, etc. All of these features are well documented on the documentation website https://gorouter.dev/
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
class App extends StatelessWidget {
App({Key? key}) : super(key: key);
final _router = GoRouter(
routes: [
GoRoute(
path: '/',
builder: (context, state) => const Page1Screen(),
),
GoRoute(
path: '/page2',
builder: (context, …
```

add go_router in Navigation category

---

source.md

https://github.com/fluttercandies/flutter_photo_manager
Add the `photo_manager` plugin, it's the base plugin of `wechat_assets_picker` introduced in #793, and `advance_image_picker` introduced in #858, providing assets abstraction management APIs without UI integration.
I've also written a summary article about the plugin recently: [Hard to manage media with Flutter? Try photo_manager, the all-in-one solution](https://medium.flutter.cn/hard-to-manage-media-with-flutter-try-photo-manager-the-all-in-one-solution-5188599e4cf)
I didn't find a proper section that matches this plugin, but the **Media** is overall the best matched, please help me to update the section if necessary.
---
**Checklist**

Add `photo_manager`

---

source.md

Repo: https://github.com/serverpod/serverpod
> [Serverpod](https://serverpod.dev/) is a next-generation app and web server, built for the Flutter community. It allows you to write your server-side code in Dart, automatically generate your APIs, and hook up your database with minimal effort. Serverpod is open-source, and you can host your server anywhere.
Also minor clean-ups (unnecessary whitespaces removed)
---
**Checklist**
---
</a>
``` 
</a>
```

Add Serverpod web framework

---

source.md

This PR replaces [Zefyr](https://github.com/memspace/zefyr) with [Fleather](https://github.com/fleather-editor/fleather). Fleather is a fork of Zefyr maintained by some of Zefyr's contributors (@Amir-P, @amantoux, ...) and since Zefyr is not maintained for almost a year and no longer working with new versions of Flutter (3.0+), I think it no longer should be on the list.
---
**Checklist**

Replace Zefyr with Fleather

---

source.md

Added  [smooth_page_indicator](https://pub.dev/packages/smooth_page_indicator) to UI section, It's so far the number on page indicator on `pub.dev
`
---
**Checklist**
---
</a>
``` 
</a>
```

Added smooth_page_indicator to UI section

---

source.md

It seems that [Planets-Flutter: from design to app](http://sergiandreplace.com/2017/09/planets-flutter-from-design-to-app) is not accessible anymore.

Fixing inaccessible link to a tutorial

---

source.md

Added a link for [weekly newsletter](https://blog.canopas.com/tagged/canopas-flutter-weekly) on new development and updates of Flutter universe.
---
**Checklist**
---
</a>
``` 
</a>
```

Add link to Flutter stack weekly

---

source.md

Hi,
This plugin provides a simple way to play multiple audio files simultaneously on android and ios. The examples are here - https://github.com/luanpotter/audioplayers.
Many features like setting playback rate, showing audio in notification area for ios are available.
I think it will be useful to lot of people.
I edited the source file according to the guidelines now.
Thanks,

add audioPlayers plugin to readMe - edited source

---

README.md
source.md

Roadmap.sh is the 6th most starred project on GitHub and a 100% and open-source developer education platform.
I have included the direct link to their flutter roadmap.
---
**Checklist**
---
</a>
``` 
</a>
```

Add roadmap.sh/flutter to Guides & Interviews

---

source.md

Added ObjectBox https://github.com/objectbox/objectbox-dart
Renamed Moor to its new name Drift https://github.com/simolus3/drift
Disclaimer: I work for ObjectBox.
---
**Checklist**

Add ObjectBox, Moor renamed to Drift

---

source.md

Added Iran Flutter community Telegram group link for users to join discussions.
[Telegram](https://t.me/persian_flutter)
---
**Checklist**
---
</a>
``` 
</a>
```

Added Iran Flutter community Telegram group link
