- README.md
- Change name of Posse's router package to new name, "fluro".  Promise we wont change it again!
- Update Posse company name to use the friendly version :)
Thanks!!
> Update Posse's asset info

- README.md
> Add Flitch to the sample open-source applications.

- README.md
Current pub entry doesn't have link to Github, so guess it's better to have the link to the repo instead
> Use Github repo for SpriteWidget entry

- README.md
> remove the obsolete swift-template project

- README.md
> added flutter-examples

- README.md
Hello! Redux.dart has been around for a while, and I recently wrote quite a bit of tooling around it lately, including a set of middleware, Time Travel DevTools, and Flutter integrations (all well tested), and therefore I think it's quite a nice solution for Flutter projects at this point.
If you think it'd make a good fit, I'd be happy to have it on this list. Thanks for putting it together and maintaining it :)
> Add Redux.dart

- README.md
An example app for people to get started with flutter_redux.
> Add flutter-redux-todo-list

- README.md
I would like to share my example project build by Flutter
> Added my open source project for sharing

- README.md
planets-flutter - open source app & tutorials
> planets-flutter

- README.md
> Added link to published apps.

- README.md
> Add Zebra EMDK link

- README.md
> Add Fluvies

- README.md
DroidKaigi 2018 is the biggest Android conference in Japan.
I created the conference app by using Flutter.
If you are okay, please add this app to `Open Source Apps` section.
https://github.com/konifar/droidkaigi2018-flutter
> Added DroidKaigi2018-flutter

- README.md
I published my open source app this week. It heavily borrows from the flutter architecture samples and I figure it's a good beginner starting point for a 'real world' app. I don't do anything particularly clever but I do have real world usage of two popular libraries (redux and sqflite).
> Add Heroes Companion

- README.md
Add the StaggeredGridView. This is a GridView widget allowing tiles to have variable sizes.
> Add StaggeredGridView in UI section

- README.md
> audio recorder

- README.md
Add a good introductory article about Flutter and how it compares to other mobile SDKs.
> What's Revolutionary about Flutter

- README.md
Adds Flutter projects I have worked on so the awesome people who visit this page can see it :)
> Proximity Sensor

- README.md
An open source map solution written in Flutter.
> flutter_map

- README.md
The new link contains the finished code for the whole project and not just the first page.
> Updated planets-flutter link

- README.md
This new YouTube channel is too good to not be on this list.
> [Videos]  Add Fluttery

- README.md
Flutter Plot is a library to create pretty plots in Flutter applications. Here is a link to the [repository](https://github.com/RCHowell/flutter_plot).
> Add flutter_plot to the Charts subsection of Components

- README.md
I added it to "Open source apps" and "Published apps", since I couldn't decide between them - should I pick either one? Don't really know what's the policy here :)
> Add inKino to Open Source Apps section

- README.md
https://github.com/trentpiercy/flutter-candlesticks
Package for creating simple and beautiful OHLC and trade volume charts
> Add Candlesticks to charts section

- README.md
Pigment is a tool for use strings color (like #FF23A1) with Flutter.
> Add pigment plugin to styling section.

- README.md
As per issue https://github.com/Solido/awesome-flutter/issues/81
> Added link to flutter_plugins_help repo, in plugins section

- README.md
I updated my link to my youtube playlist. And removed my twitter link.
> Updated my link

- README.md
- Fixed Description for "App Rating" Plugin
- Added "Get Version" to Plugins
> Updated "App Rating" and Added "Get Version" 

- README.md
https://github.com/google/flutter_flux
> Add flutter_flux

- README.md
This list is awesome, @Solido (pun intended)!
I've seen some of your previous effort towards meeting all the silly rules to entering the [Awesome Awesome](https://github.com/sindresorhus/awesome), and I understand you might be frustrated about the futility of some things they say.
But I think it'd be very good for this awesome and for the Flutter community as a whole to get a place there, so I took the liberty to fill (I think) all their remaining requirements, so, when you merge, I hope we can re-open that request.
I'm prepared to fix any other complaints they might have afterwards (if they still do) ;)
> Fixes for entering Awesome Awesome

- source.md
Photo view is a component that makes an image sensor scale gesture. [Since rotation gesture is still to be implemented to flutter](https://github.com/flutter/flutter/pull/17345), PhotoView has this as a plan to the future yet.
https://github.com/renancaraujo/photo_view
> Add PhotoView

- source.md
This seems like it could fit in Image or UI, but Image makes sense to me.
> Add Flutter SVG

- source.md
See also #119 for discussion on Android specificity
> Add Android Job Scheduler Plugin (Android Specific)

- source.md
Flutter UI Kit with full of real life scenario.
> Flutter UI Kit by Pawan Kumar added in Templates

- source.md
Thanks for adding the project!
I agree, moving in the direction of Yeoman where the library supports many different architectures would be great. Just need to find the best way to implement it...
> Added Redux starter/code generator

- source.md
Still under development though, so this PR can stay open pending when its done and documented. 
I wanted it out there to also see if i can get contributors or help before initial release seeing i'm also a bit new to this. 😄
> chore: adding SpinKit

- source.md
Simple Api requests with built in authentication. Includes a code generator for easy serialization/deserialization.
> Added simple_auth

- source.md
GraphQL queries and mutations implemented with easy to use Flutter widgets.
> Added graphql_flutter

- source.md
French and English blog dedicated to providing practical solutions to most asked questions about Flutter
> add link to didierboelens.com

- source.md
https://github.com/trentpiercy/trace
Full-featured crypto portfolio and market explorer. Reason I made the candlesticks lib currently in the charts section :)
> Add Trace to Open Source Apps

- source.md
Started this video series a few months ago, and have been publishing new videos regularly.
People seem to really like it :) Example video: https://youtu.be/RJEnTRBxaSg
Would be great to have it included on this list.
Many Thanks.
> Add Coding With Flutter YouTube video series

- source.md
Hi,
you asked me if I would like to join your list therefore I'm opening this pull request.
This is a plugin for getting a persistent UDID across reinstalls on iOS and Android.
> Flutter UDID

- source.md
AudioRecorder and AudioPlayer at one hand with streaming.
> Add flutter_sound plugin.

- source.md
As requested by Solido via Discord DM
> Created the community category, added link to FlutterDev discord/reddit

- source.md
A fresh new todo list app built with flutter inspired by a design
> Add Taskist to Open Source Apps

- README.md
- source.md
> Fix chart heading

- source.md
> Update source.md - Added AppAvailability and InAppBrowser plugins

- README.md
> add stepper touch

- source.md
> Animated Text Kit

- source.md
- new blog
- new ui element
- new device element
</a>
``` 
</a>
```
> New Content by diegoveloper was added

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ?  👍 
Flutter NFC reader provides a quick way to read NFC tag on both iOS and Android using flutter
> add flutter nfc reader

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? 👍
A tidy utility to handle offline/online connectivity like a Boss. It provides support for both iOS and Android platforms (offcourse).
</a>
``` 
</a>
```
> Added Offline UI Plugin

- source.md
A multi-part tutorial about Flutter's rendering engine
> add rendering engine tutorial

- source.md
> Trinity Orientation

- source.md
Hi Robert,
I finally managed to make the PR for the InheritedWidget article as you suggested me.
What I didn't remember well was the section where to place it. If it does not fit in the Advanced one, please, let me know and I will change it.
By the way, I have this open source app https://github.com/jmolins/flutboard that is also published on Google Play. Don't know if it deserves appearing here. If you think so, just let me know.
Thanks for everything and for this awesome repository.
> Add article about InheritedWidget and App state

- source.md
You asked for it in the article [here](https://medium.com/@BlueAquilae/youre-welcome-to-commit-a-pr-for-your-article-on-awesome-list-under-the-howto-section-4c2cac08330d) 👍 
It tells about Animations in Flutter.
> Add Animations in Flutter to list

- source.md
My InAppBrowser plugin changed a lot, so I have updated its description! 
I will add also the badge to my repos 😄 !
> Updated InAppBrowser plugin description

- source.md
This small library can create a list which will snap to the closest item when the user stops dragging. This is useful when you want to show one list item at a time, without allowing the user to quickly scroll through the entire list.
> Adds Snaplist to the UI section

- source.md
Link to the package ---> [flutter_fluid_slider](https://github.com/rvamsikrishna/flutter_fluid_slider)
It is awesome because :
- A cool and minimal design
- Well documented
- Ease of use - just drop it into a widget tree like the regular material slider
- Easily customizable
- Provides all the callbacks that the basic slider does
- The animation allows you to see the current value while dragging
> Add Fluid Slider to the UI category

- source.md
The purpose of this project is to support the Flutter framework on Windows, MacOS, and Linux using a SINGLE codebase. It sounds familiar, does it not?
> Add Golang Desktop Embedder to the Utilities section

- source.md
> Add fluttercrashcourse.com to Videos section

- source.md
Link to the repo: https://github.com/Sh1d0w/multi_image_picker
> Add multi_image_picker plugin

- source.md
The purpose of this article is to show a tutorial to make it easy for any developer to run it Flutter project on desktop environment using the project at https://github.com/Drakirus/go-flutter-desktop-embedder.
> Add Flutter: from Mobile to Desktop to the Advanced Articles section

- source.md
> added flutter_ibm_watson

- source.md
Link to the package ---> [wave](https://pub.dartlang.org/packages/wave)
Link to the repository ---> [i-protoss/wave](https://github.com/i-protoss/wave)
> Add wave effect.

- source.md
Tutorial link: https://github.com/lesnitsky/todolist_flutter
App screenshot:
> Add Todo List tutorial

- source.md
Added DrawApp under Templates. Sample drawing app which demonstrates how to allow the user to draw onto canvas. Also comes along with a with color picker and brush thickness slider.
[Link to DrawApp repo.](https://github.com/SnakeyHips/drawapp)
> Added DrawApp Template.

- source.md
> Added Mixpanel Analytics

- source.md
Add `file_picker`
**Description:**  File picker plugin alows you to use a native file explorer to load absolute file path from different types of files.
> Add File Picker plugin

- source.md
</a>
It's a Flutter widget for entering pin code. Suitable for use cases such as login and OTP.  [link](https://pub.dartlang.org/packages/pin_code_text_field)
``` 
</a>
```
> Added pin code text field

- source.md
Recipe App UI template using pure Flutter. 
Inspiration from [this awesome dribbble](https://dribbble.com/shots/5299031-Recipe-Sharing-Food-Channel). 
[Link to repo](https://github.com/SnakeyHips/recipeapp).
> Added RecipeApp Template.

- source.md
This is an app showcasing different components of Flutter, with preview and source code side-by-side.
It's quite handy to quickly look up for something you want to achieve.
C.f. https://github.com/X-Wei/flutter_catalog
> Add flutter catalog

- source.md
A great guide by example on layout widgets and their possibilities, by Tomek Polański. It's a great way to visually understand the differences between all of the different kinds of widgets.
> Add Flutter Layout Cheat Sheet to Howtos Section

- source.md
Added this article by Pooja Bhaumik (myself) - https://medium.com/flutter-community/i-want-to-learn-flutter-how-to-start-ffb4145f9b26 under the "Begin With" category. This is a step by step guide for learning Flutter for super beginners, personalized with my own trial and error experiences. And also contains a list of useful tips & plenty of amazing resources from the flutter community. Already has 1.2K claps on Medium
Hope this gets merged!
> Added "I want to learn Flutter. How to start?" article

- source.md
Add package HIdden Drawer menu a beautiful drawer mode menu feature with perspective animation.
I think you're right now ^^
</a>
``` 
</a>
```
> adicionando package hidden_drawer

- source.md
A new way of writing widgets (because hooks are not enough 😄)
Writing classes is quite boilerplatish, which is unfun. Functions are cool~ But they are not associated with an Element/can't have keys/... So they are a no go.
Let's fix this and generate classes from functions!
> Add functional_widget

- source.md
Just adding the Chicago Meetup group to the list of communities
> Add United States and Chicago to the Community groups

- source.md
fix double input of flux framework
</a>
``` 
</a>
```
> fix double input

- source.md
This is a collection of various official components (demos) to help developers learn flutter quickly. Provided by Alibaba Auction Frontend Team.
> Added "Flutter-Common-Widgets-App" to Open Source Apps Section 

- source.md
> Added meetup group for danish developers

- README.md
> Added reference to MobX with a separate section on State Management

- README.md
- source.md
A starter kit for beginner learns with Bloc pattern, RxDart, sqflite, Fluro and Dio to architect a flutter project. This starter kit build an App Store app as a example
> Add flutter starter kit with App Store demo app

- source.md
Hey @Solido , finally I am able to send the blog post about accessibility and the German community links. :)
> Add German community and new blog post about accessibility.

- source.md
Hi, I've created a flutter desktop embedder in rust and added to the list.
> Added flutter desktop embedder in rust

- source.md
Can be found at [TailorMade](https://github.com/jogboms/tailor_made).
</a>
``` 
</a>
```
> chore: added TailorMade (#1)

- source.md
Added a line on Bitrise Flutter build automation, plus changed the anchor text for the Flutter step in Go to actually reflect the contents being linked to
</a>
``` 
</a>
```
> Added Bitrise Flutter build automation

- source.md
> chore: add lagos(Nigeria) community

- source.md
It's a library with the intent to simplify the using of streams and BLoC pattern, furthermore, various widgets (blur, transitions, timed widgets, sliders, animated waves etc.).
> added frideos library to "Misc" section

- source.md
How to get started with Codemagic and automatic code signing for iOS without Mac
</a>
``` 
</a>
```
> Add Codemagic CICD for Flutter

- source.md
Provides a wrapper library so devs can access the AppAuth SDKs via Flutter
> add flutter_appauth plugin

- source.md
http://howtodothisinflutter.com
> Add howtodothisinflutter

- source.md
✔️ Beatiful UI and great UX
✔️ Current weather: current temperature, max and min temperature, humidity, pressure, wind
✔️ Current sun/moon position, animated countdown until sunset/sunrise, time of sunset/sunrise
✔️ Weather forecast for 5 days (temperature, wind, rain and pressure)
✔️ Custom-written chart with animation
✔️ Sun/moon animation
✔️ App background based on day cycle
✔️ Automatically picks user location (also error handling when location can't be selected!)
✔️ Persist location and weather data in local storage
✔️ Works offline (user need to download data before)
✔️ Automatically refresh data every 15 minutes
✔️ I18n support (currently PL and EN)
✔️ Bloc architecture, Dio and RxDart libs
✔️ Unit and widget tests
✔️ Travis CI and Bitrise
> Feather - weather application

- source.md
Hey Robert!
I recently finished a dart-only animation library which allows to animate SVG paths in a drawing-like fashion. I'm currently a student and therefore have some reasonable amount of time (and passion) to care for the project :-)
See some examples:
https://github.com/biocarl/drawing_animation
and pub: https://pub.dartlang.org/packages/drawing_animation
> Add drawing animation library to awesome-flutter

- source.md
A GeoFire implementation for firestore, to query documents based on GeoLocation. Checkout this awesome tutorial by Jeff featuring this plugin - [https://youtu.be/MYHVyl-juUk](https://youtu.be/MYHVyl-juUk)
> Added GeoFlutterFire plugin

- source.md
GitTouch is an open source GitHub client built with Flutter.
Repo here: https://github.com/pd4d10/git-touch
> Add GitTouch - Open source GitHub client

- source.md
`AutoSizeText` is a useful tool for resizing text to the correct size.
Repo: https://github.com/leisim/auto_size_text
> Add AutoSizeText

- source.md
Added Lottie plugin to list under the section titled images
> Added Lottie plugin under images

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? 
-> Yes.
-> The [Reorderables](https://pub.dartlang.org/packages/reorderables) package solved the problem of reordering rows of table, elements of row/column, and elements of wrap (grid-like reorderable widget also possible by setting an optional parameter).
-> Will do.
</a>
``` 
</a>
```
> Add Reorderables to UI

- source.md
> add Tetris to Games

- source.md
`table_calendar` serves as an interactive calendar, which will autosize vertically. Thanks to this feature, developers can easily add supplementing widgets to the same screen (eg. a ListView showing a list of events scheduled for selected date - example included).
Repo link:
https://github.com/aleksanderwozniak/table_calendar
> Add table_calendar package to Components

- source.md
Reorderables added support to SliverList, hence updating the description here.
> Update description of the reorderables package.

- README.md
- source.md
According to the comment you left [in my repo](https://github.com/pszklarska/beacon_broadcast/issues/1) 👍
> Added beacon_broadcast library under "Bluetooth" section

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? - **yes**
</a>
``` 
</a>
```
> Flutter Files for VSCode

- source.md
> Add `Flutter Debugger` and remove `flutter_flipperkit`

- source.md
This plugin help developers to access VPN service in their flutter app.
The Android part was implemented by strongswan which support ikev2 protocol.
The iOS part was implemented by NEVPNManager.
> Add flutter vpn plugin

- source.md
Here is a Bottom Navigation,
That is an implementation of [this artwork](https://www.uplabs.com/posts/bottom-tab) on uplabs.com
> add Circular Bottom Navigation on source.md (Ui section)

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? right
</a>
``` 
</a>
```
> Added BottomNavyBar widget plugin

- source.md
> Add flutter_xlider to list

- source.md
Yes :)
I propose to add a new "Augmented Reality" section. It should be in use for ARCore and cross-platform XR plugins.
> Add "Augmented Reality" section and "ARKit Plugin"

- source.md
> Add camera ml vision plugin on scanner category

- source.md
`Flutter in Practice` is a free video course for beginners & non-programmers about Flutter & Dart. It's hosted on YouTube for convenience.
Instead of teaching concepts and ideas in both Flutter and Dart, this course showcases a process of building an actual, mobile application.
> Added `Flutter in Practice` Video Course

- source.md
Chinese are unable to use Google Maps because of the GFW, and AMap is the largest map in China.
> Add AMap(高德地图)

- source.md
Yes. 
With ARCore Flutter Plugin you can:
- add 3D object on the real world (anchored on the plane or based on the camera position)
- customize your 3D object (shape, color, texture, mettallic, roughness , reflectance property)
- plane detection
- plane tap detection
- node tap detection
- other features (cooming soon)
The plugin is only for Android (for now). I'd like add iOS compatibility in the future.
Thanks
> Add "ARCore plugin"

- README.md
- source.md
> add Spacex-Go to open source apps

- source.md
By this i am solving this issue :-)
https://github.com/felixblaschke/simple_animations/issues/10
> added Simple Animation as animation framework

- source.md
Rubber is a highly customizable bottom sheet that provides:
* Up to 3 stopping points
* Spring animations
* Scroll and drag seamlessly
* Dismissable behavior
> Add Rubber Bottom Sheet to UI

- source.md
Can be used to do nice page transition.
Extensively used in our app MoodRise (available on iOS and Android).
</a>
``` 
</a>
```
> Add Slide Container to UI

- source.md
> Collection of useful UIs clones by Javier González  added in Templates

- source.md
> Added Meetup for Hamburg, Germany

- source.md
@Solido 
Sorry for the Typo for star count of AspectD.
I've fixed it.
> Typo for star count.

- source.md
I've added the FilledStacks website to the Websites / Blog section. I cover everything from basic Flutter (how to parse json) topics to the large ones like setting up your application's architecture using proivder. 
In addition to weekly video tutorials I also have a single repo that contains all the source for every tutorial so far and I make additions to it weekly.
> Added FilledStacks Blog and Tutorial Repo

- README.md
- source.md
> UI section: Superhero interaction app link added.

- source.md
Yes.
Added Toronto Flutter meetup to source.md, mimicking the Chicago entry.
</a>
``` 
</a>
```
> Add Canada and Meetup Toronto

- source.md
`Logger` is an easy to use logging library which improves visibility of logs.
Repo: https://github.com/leisim/logger
> Add Logger

- source.md
added FL Chart library on the charts section
> Added FL Chart on the Charts section

- source.md
`Direct select` is a selection widget with an ethereal, full-screen modal popup displaying the available choices
Repo: https://github.com/LanarsInc/direct-select-flutter
> Add direct select

- source.md
More details in this link:  https://twitter.com/diegoveloper/status/1138127116069941248
> Bezier_chart widget was added

- source.md
> add dynamic_widget to UI category

- README.md
> add Scroll to index

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right?
Yes
Added Sri Lanka and Colombo Flutter Community to source.md.
</a>
``` 
</a>
```
> Added Sri Lanka and Colombo Flutter Community

- source.md
The inview_notifier_list package helps create a list view and notify when intended widgets are on a screen within the area which the user can provide.
It is helpful in scenarios like:
- autoplay videos
- add real-time update listeners from database to content only visible on the screen.
It is also tested.
> added inview_notifier_list package to ui helpers section

- source.md
The project uses Flutter/Web as its front-end to give the control of the LEDs on SenseHat on RPI.
My contribution: 
- It shows a minimum combination of Flutter/Web, BLOC, and WebSocket to work with a Go server.
- This can be an option for someone who has the SenseHat of RPI in his/her drawer for a while but also interested about Flutter/Web.
> Added Matrix2 in the Game category.

- README.md
- source.md
> add 🇦🇴 community

- source.md
_You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ?_ Yes
Adding the Meetup page of Flutter Portugal Community 🇵🇹
> Add Flutter 🇵🇹 Portugal community

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? Yup :) 
http://flutterevents.com
</a>
``` 
</a>
```
> Add Flutter Events

- source.md
This repository contains a list of helpful Flutter related questions you can use to interview potential candidates. This is an open source project, feel free to contribute.
> Added 'Jobs/Interview Questions' Section

- source.md
I Added FlutterFoodybite a Flutter made UI template inspired by an uplabs post. It currently has 150 stars as at the time i am writing this. Link: https://github.com/JideGuru/FlutterFoodybite
Thanks for your Considerations
</a>
``` 
</a>
```
> Added FlutterFoodybite

- source.md
Enigma is a full-featured, privacy centric one-to-one chat app that has all the mainstream features like online and typing indicators whilst also providing users greater control of their individual chats which can be hidden or locked which would require a passcode/fingerprint authentication.
</a>
``` 
</a>
```
> Added Enigma - a full-featured chat app.

- source.md
> Added UK & London

- source.md
Yes.
Adding FlutterSP (São Paulo) Meetup to Brazil section.
</a>
``` 
</a>
```
> Add Flutter São Paulo Meetup

- source.md
- FlutterX is a new site which compiles all resources from the Flutter Weekly newsletter and make them full-text searchable. 
- I don't have the time to actively support the IntelliJ plugin so think it's best not to list it. 
</a>
``` 
</a>
```
> Added FlutterX and removed IntelliJ Redux

- source.md
The first Flutter music application made with **Provider and Bloc pattern**. Unlike other Flutter music applications, Chillify provides a smooth experience and easy interactions with fancy UI.
Repo: https://github.com/KarimElghamry/chillify
> Added Chillify to Open Source Apps

- source.md
Liquid swipe is the revealing clipper to bring off amazing liquid like swipe to stacked Container.
Repository : https://github.com/iamSahdeep/liquid_swipe_flutter
Thank you
Preview :-
> Added Liquid Swipe to Effects

- source.md
Whatsupcoders is a free knowledge base of Flutter video tutorials on a variety of topics. The videos are based on Flutter Widgets applied to real-life use cases beyond just a rudimentary explanation.
> Added 'Whatsupcoders' video series

- source.md
I have read the guidelines.
I have added 2 awesome meetup groups to the Canada section of Communities. 
This is my first PR ever. Hope I don't break the internet!
> Added Calgary, Montreal meetups to Communities in Canada

- source.md
A Pokedex app with beautiful UI and smooth animation
Repo: https://github.com/scitbiz/flutter_pokedex
> Added Pokedex to Open Source Apps

- source.md
Add Flutter-Animation-Set v0.0.2
</a>
``` 
</a>
```
> Add Flutter-Animation-Set v0.0.2 into Animation，Thanks

- source.md
> Added Flutter Turkish Community.

- source.md
Peek & Pop, in my opinion, is a revolutionary method of navigation for applications and I'm quite confident of the quality of this Flutter adaptation. 
PS: This package is very easily convertible to "Context Menus" when they are released.
> Added "peek_and_pop" to a new "Cupertino Design" category.

- source.md
> Added Flutter Widget Live Book to Website/Blog

- source.md
[flick](https://github.com/aliyigitbireroglu/flutter-flick) was actually designed to be used with [snap](https://github.com/aliyigitbireroglu/flutter-snap) but I found it to be a very useful component so I switched it to a standalone package. Flicking has a good place in UI/UX development which is why I believe it can be helpful to other developers as well.
> Added "flick" to UI Helpers

- source.md
A Flutter package to parse text and extract parts using predefined types like url, phone and email and also supports Regex.
pub: https://pub.dev/packages/flutter_parsed_text
Github: https://github.com/fayeed/flutter_parsed_text
> Added flutter_parsed_text to Text & Rich Content

- source.md
A Flutter package that enables the use of Gherkin feature files to automatically test any Flutter UI.  Very similar to CucumberJS in that tests can be written in plain language.
https://github.com/jonsamwell/flutter_gherkin
Tests can be written using feature files (like below) which is then translated and ran as an automated UI test via the interaction with the flutter_driver.
```
Feature: Counter
The counter should be incremented when the button is pressed.
Scenario: Counter increases when the button is pressed
Given I expect the "counter" to be "0"
When I tap the "increment" button 10 times
Then I expect the "counter" to be "10"
```
> Added flutter_gherkin to the list of test resources

- source.md
This package allows to easily add staggered animations to ListView, GridView, Column and Row children :
https://github.com/mobiten/flutter_staggered_animations
> Add the flutter_staggered_animations package

- source.md
> add flutterparainiciantes - brazil community

- source.md
New plugin for audio recording, it provides full controls(start/pause/resume/stop) and access to recording details(such as level metering) while recording.
> Added new plugin - flutter_audio_recorder

- source.md
> Fixed broken link

- source.md
> Add Flutter's Greek Community

- source.md
Sure thing, I got the contribution stuff ✅
> Added Meetup for Tricity

- README.md
This is to fix the incorrect description I put in from my copy and paste mistake made in https://github.com/Solido/awesome-flutter/pull/315/files ^^;
> fix description of Flutter AppAuth plugin

- source.md
Package that allows you to showcase your features on iOS and Android.
[flutter_showcaseview](https://github.com/simformsolutions/flutter_showcaseview)
Thanks
> Added showcaseview package to new section named ' Tooltip '

- source.md
We are planning for talks, Meetups and charity works in Kurdistani Region where the main language of its people is Kurdish.
> Adding Flutter Kurdistan Meetup group

- source.md
This is one o the first plugins to use the Dart FFI.
With bitmap, one can edit images in a Flutter app.
> Added new plugin - Bitmap

- source.md
Group messaging app with a focus on organizing events.
Repo: https://github.com/janoodleFTW/timy-messenger
> Add Timy messenger to open source apps

- source.md
> Add 🇮🇩 Telegram Group

- source.md
Simply added the link to the Flutter Stuttgart Meetup website.
We are looking forward to having more people over to our Meetups.
We had five Meetups so far and we are currently planning the next one in November.
Therefore it would be great, if the Meetup is listed up here :)
> Flutter Meetup for Stuttgart (Germany) added

- README.md
Hi @Solido,
I have added Photofilters library under Image.
Thanks
> Added Photofilters library

- README.md
- source.md
@YoussefKababe has transferred the[admob_flutter](https://github.com/kmcgill88/admob_flutter) repo to me. I've updated the URL and added myself as an author. I added iOS support to the plugin and recently added [bitrise CI](https://app.bitrise.io/app/aab4844dfe687df4#/builds) to improve quality.
> Update admob flutter

- source.md
> Add Korea Community link

- source.md
This is a package I created a few weeks ago. It's not very popular, but it may be in the future (since similar packages in other frameworks are). Also, it's very well documented and tested, so I think it deserves a space in here 😊
https://pub.dev/packages/drag_select_grid_view
> Add drag_select_grid_view

- source.md
- Scoped models for state management
- Internationalization in place (English and Polish languages)
- Clean Material Design
- Use sensors (accelerometer) as alternative game controller
- Firebase analytics with custom events
- Crashlytics reporting
- Released on both - Android and iOS 
- More than 10,000 downloads
- Mature and stable product
- Layout adjusted for phones and tables
> Add Zgadula to Open Source Apps

- source.md
I have renamed my profile form Drakirus to pchampio.
> chore: github username rename

- source.md
As requested, I am resubmitting this pull request with the conflicts resolved because apparently I've already removed the previous fork from my repos.
> Added "image-sequence-animator" to UI

- source.md
> add Norway user groups

- source.md
I just added the [Titled Navigation Bar](https://github.com/pedromassango/titled_navigation_bar) package a cool and beatuiful navigation bar that change the item icon by the item title when selected.
``` 
</a>
```
> Added a new Bottom Bar package

- source.md
Flutter Turkey Slack link updated and Youtube link removed.
</a>
``` 
</a>
```
> Flutter Turkey Slack link updated and Youtube link removed.

- source.md
> Add UI package:  `Flutter_beautiful_popup`

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right - Yes
This is a package for deep link navigation that I've been working on for about a month, it's pretty well documented and UI tested, and would love it share it with the Flutter community!
**Dart Pub** 
https://pub.dev/packages/deep_link_navigation
**Github**
https://github.com/Dennis-Krasnov/Flutter-Deep-Link-Navigation
> Added "Deep Link Navigation" to Navigation

- source.md
Added new flutter london website link
> Added flutter london website link

- source.md
[Flutter Login] is the package I wrote to familiar myself with Flutter and animation in particular. It has a lot of animations to demonstrate the cababilities of Flutter. I tried to keep it close to 60fps so the animations look slick in general.
<p align="center">
<a href='https://i.imgur.com/z3FJSe7.mp4'>
</a>
</p>
[Flutter Login]: https://github.com/nearhuscarl/flutter_login
> Add FlutterLogin

- source.md
- added links to Polish, Warsaw, Wrocław and Poznań Flutter communitites
> Update Polish Flutter communitites

- source.md
I would like to add the Madrid Flutter Community in the awesome flutter repository :)
> Add Spain Community

- README.md
> Added Flutter Philippines to the list of communities

- source.md
@Solido I have added my image cropping package to the list.
> Adds Crop package under Images section.

- source.md
I added a new country social links (Peru)
> New country links

- source.md
Add flutter_shine.dart and flutter trianglify
> Add Flutter_shine an Flutter trianglify

- source.md
I added a new collection of Flutter samples inside TEMPLATE category (It has more than 450 stars).
> New Template item

- source.md
This project started as a an exploration into the state of Flutter and how it would support a bigger team-based development effort with everything that is needed to make a production-quality app and maintain it over time. Once pulled together, it made sense to share it as a possible starting point for others, as well as update it with the progress of Flutter, libraries, and tooling.
More details on the app: 
https://stuff.greger.io/2019/07/production-quality-flutter-starter-app.html and about the latest updates:
https://stuff.greger.io/2020/01/production-quality-flutter-starter-app-take-two.html
> Add first_app (production-quality starter app for teams)

- source.md
> Added a beginners article on a Flutter developer roadmap

- source.md
Flutter Echarts has the capability to build complex charts like WebGL 3D chart and GIS map, whitch other flutter charting libraries can not do.
It has got some users and got a score of 90 on pub.
I would really want to share it with more people.
Thanks!
https://pub.dev/packages/flutter_echarts
https://github.com/entronad/flutter_echarts
> Add Flutter Echarts, a charting widget

- source.md
Hi. I added a links to local Flutter community in Ukraine.
> Added Ukraine communities

- source.md
Added a section on print books with links to the Amazon pages and links to the authors of the books.
> Added Books section with links to Amazon

- source.md
Hi, GitTouch supports GitLab, Bitbucket and Gitea now. This PR updated its description
Repo here: https://github.com/pd4d10/git-touch
> Update GitTouch: Open source mobile client for GitHub, GitLab, Bitbucket and Gitea

- source.md
> Updated source.md to include Flutter PH Community

- source.md
This is not my repo. I found this a while back and decided to contribute some code to allow it to work with Dart, and therefore Flutter. The ML section is definitely lacking and I have not seen a lot of effort in the industry outside of Tensorflow to get some sort of good ML package for Flutter devs. This adds to that effort by allowing a dev to train a full model on their data and then convert it to Dart code with no dependencies.
https://github.com/BayesWitnesses/m2cgen
> m2cgen converts ML models into native Dart code

- source.md
Hello there. A while back you suggested that I submit Clay Containers here, so I am doing so.
I am humbled by your suggestion, and not sure if my repository is worth such a list, but here it is.
Clay Containers is a package which provides primitive widgets (currently just container and text widgets), which make the creation of nuemorphic designs easier. 
Thank you for your consideration.
> Add Clay Containers

- source.md
Old repositories doesn't exist anymore.
> Update Firebase Repositories

- source.md
Hi @Solido  ,
This app is an implementation of a credit card input form.
Repository : https://github.com/Origogi/Flutter-Credit-Card-Input
> Add credit carm form in UI category

- source.md
Hi @Solido , I fix wrong letter
> fix from to form

- source.md
Creating a "gaming" section and adding [Awesome Flame](https://github.com/flame-engine/awesome-flame) link.
> Adding gaming section plus Awesome Flame link 

- source.md
[styled_widget](https://github.com/ReinBentdal/styled_widget) a useful UI helper to simplify widget trees thanks to extension methods.
> Add styled_widget

- source.md
Yes, I have read the contribution guide. Flutter Pakistan Community Facebook group is for Pakistani Developers and beginner's place to share knowledge and learn.  
</a>
``` 
</a>
```
> Add Flutter Pakistan Community Facebook Group

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? sure
I created a visual scheme with step-by-step guidance for Flutter newbies and I hope it might be useful for the community.
</a>
``` 
</a>
```
> Add "Highly Subjective Roadmap to Flutter"

- source.md
This is a Flutter package for **trimming videos** with a decent UI/UX.
Link to the package on **pub.dev**: [video_trimmer](https://pub.dev/packages/video_trimmer)
* Customizable video trimmer
* Video playback control
* Retrieving and storing video file
* Also supports conversion to GIF
> Add Video Trimmer package

- source.md
Largest Malaysian Flutter community  in Telegram.
> Added Malaysia Flutter Telegram group.

- source.md
Source: <https://github.com/flutter/flutter/blob/master/examples/flutter_gallery.readme>
> Update official gallery link

- source.md
</a>
``` 
</a>
```
FadeIn Animations 
FadeIn
FadeInDown
FadeInDownBig
FadeInUp
FadeInUpBig
FadeInLeft
FadeInLeftBig
FadeInRight
FadeInRightBig
FadeOut Animations 
FadeOut
FadeOutDown
FadeOutDownBig
FadeOutUp
FadeOutUpBig
FadeOutLeft
FadeOutLeftBig
FadeOutRight
FadeOutRightBig
BounceIn Animations 
BounceInDown
BounceInUp
BounceInLeft
BounceInRight
ElasticIn Animations 
ElasticIn
ElasticInDown
ElasticInUp
ElasticInLeft
ElasticInRight
SlideIns Animations …
> Add animate_do

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? 
> YES
> Instant Messaging community was moved to Telegram to accommodate the growing number of devs.
</a>
``` 
</a>
```
> Update FlutterLagos community channel

- source.md
You've read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md) right ? YESS!!
[Modal button sheet](https://github.com/jamesblasco/modal_bottom_sheet) is a package to improve the limitations of flutter modals .
Some of the key features it is that allows to use the new iOS 13 modal navigation and you can dismiss a modal with a scroll view inside by gesture.
You can try the online demo here:[https://jamesblasco.github.io/modal_bottom_sheet/#/]( https://jamesblasco.github.io/modal_bottom_sheet/#/)
</a>
``` 
</a>
```
> Add Modal Bottom Sheet package

- source.md
</a>
``` 
</a>
```
One month ago I’ve been working on a Flutter project with different flavors. This was the first time in Flutter, and it’s been pretty tedious. That's why I've created the flutter_flavorizr library, a tool which easily flavorizes your Flutter application in less than 3 minutes. It works for both Android and iOS destinations.
Just define your flavorizr configuration in your pubspec.yaml
```
flavorizr:
app:
android:
flavorDimensions: …
```
> Added flutter_flavorizr (medium news + github)

- source.md
I added it under the UI header. I would be glad if you review it. Thanks.
> Add animated selection slide for UI header.

- source.md
You've read How to contribute right ?
Yes
Flutter tags simplifies the dynamic creation of selectable tags or input with textField.
[flutter_tags](https://github.com/Dn-a/flutter_tags)
Thanks
>  Add "Flutter Tags"

- source.md
It's a simple app I've been developing to store my journal entries in a Git Repo. It stores them in Markdown + YAML header.
> Add GitJournal to Open Source Apps

- source.md
</a>
``` 
</a>
```
[Link to pub.dev](https://pub.dev/packages/flutter_tex)
[Link to GitHub](https://github.com/shah-xad/flutter_tex)
A Flutter Package to render so many types of equations based on **LaTeX** and **TeX**, most commonly used are as followings:
- **Mathematics / Maths Equations** (Algebra, Calculus, Geometry, Geometry etc...)
- **Physics Equations**
- **Signal Processing Equations**
- **Chemistry Equations**
- **Statistics / Stats …
> Added Flutter TeX package

- source.md
Added Open source game - Ghost Rigger, a cyberpunk-inspired puzzle game set in a dystopian future:
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Open source game - Ghost Rigger

- README.md
---
**Checklist**
---
</a>
``` 
</a>
```
> Added flutter india details

- source.md
FlutterNeumorphic is a complete ui kit like material or cupertino, but implementing neumorphic design
It has a lot of widgets, and handle multiple shadow modes, with inner & outer shadows (for positive & negative depth)
---
**Checklist**
---
</a>
``` 
</a>
```
> Added FlutterNeumorphic

- source.md
---
**Checklist**
---
</a>
``` 
</a>
```
> Add Appcircle CI/CD tool for Flutter

- source.md
added somecalendar to the list of calendar widget
**Checklist**
---
</a>
``` 
</a>
```
> add somecalendar to the list of calendar widget

- source.md
Largest Indian Flutter community in Telegram.
> Added Indian Flutter Telegram Group

- source.md
#384  Description
My [YouTube channel](https://www.youtube.com/channel/UCrTnsT4OYZ53l0QGKqLeD5Q) contains a growing collection of over 50 free videos about Flutter app development.
---
**Checklist**
---
</a>
``` 
</a>
```
> Add link to Code With Andrea YouTube channel (Flutter Tutorials)

- source.md
Dough is an open source UI toolkit which gives developers simple tools to create squishy user interfaces. https://github.com/HatFeather/flutter_dough
---
**Checklist**
> Added Dough Package to UI Category

- source.md
Fontify package provides a CLI tool and an API for generating icon font from SVG icons and Flutter-compatible class. And it is written fully in Dart.
I made this project because there was no such converter that wouldn't require external dependency like Node.JS. My team had been using the "fluttericon" website for more than a year, but now my tool is used instead. It's much more convenient.
https://github.com/westracer/fontify
---
**Checklist**
> Added Fontify (CLI tool for generating icon font)

- source.md
---
**Checklist**
---
</a>
``` 
</a>
```
> Added FlutterGen

- source.md
- Add job board websites
- Add job in summary contents
---
**Checklist**
> Improve jobs section

- source.md
A working Twitter clone written in Flutter using Firebase auth,realtime,firestore database and storage. 
Project link:- https://github.com/TheAlphamerc/flutter_twitter_clone
App link:- https://play.google.com/store/apps/details?id=com.thealphamerc.flutter_twitter_clone
Fwitter is not just a UI clone of twitter it has functionalities like Twitter. User can create tweets and comment on them. Every comment is itself a tweet so it can also have a comment tweet thread. This enables the user to create a nested tweets.
Apart from tweet Fwitter has several functionalities like Profile view, notification view, 1-1 message, Tag user in tweet etc.
Detail functionalities can be found at :- https://github.com/TheAlphamerc/flutter_twitter_clone/projects
Some more details about twitter :- …
> Add Fwitter app link to Open Source Apps section

- source.md
- Add podcast section and three podcast in different languages
Podcast about all things, grow more and more over the years.
Currently, there are several podcasts about Flutter with really nice information. Everyone needs to discover this great resource to learn Flutter.
---
**Checklist**
> Add podcast section

- source.md
fix a broken link for the book Flutter in Action
---
**Checklist**
---
</a>
``` 
</a>
```
> fix a broken link

- source.md
This is smart washing machine app template.
The main curiosity is the use of the Box2D physic engine inside the flutter to simulate the washing machine drum and "metaball" effect.
[GitHub Repo](https://github.com/pawlik92/flutter_whirlpool)
---
**Checklist**
> Added smart washing machine template app

- source.md
JohannesMilke is a free knowledge base for Flutter video tutorials on a variety of topics. The videos are based on Flutter for beginners and advanced developers with applications close to real-life use cases and beyond just rudimentary explanations.
> Added 'JohannesMilke' video series.

- source.md
Discretly adding Camerawesome in video plugin section... :)
---
**Checklist**
---
</a>
``` 
</a>
```
> Add camerawesome in videos plugins section

- source.md
Add info and links for the "Flutter Munich" (Germany) meetup group.
---
**Checklist**
> Add Munich meetup group info

- source.md
Ferry is a GraphQL Client, offering a normalized optimistic cache and a powerful, extensible API.
You can find the documentation here:
https://ferrygraphql.com/
---
**Checklist**
---
</a>
``` 
</a>
```
> Add Ferry GraphQL Client

- source.md
---
**Checklist**
---
</a>
``` 
</a>
```
> Adding Israel facebook group to SOURCE.md 2

- source.md
Hey @Solido 
just fixing a dead link to the GitHub instead.
Cheers!
> Moving dead link to GitHub instead

- source.md
Added [Flutter Form Builder](https://github.com/danvick/flutter_form_builder) package under _Widgets Framework_.  This package simplifies form creation, field validation, and gathering the form input.
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Form Builder to Widgets section.

- source.md
Added **[timelines](https://github.com/chulwoo-park/timelines)** to UI section.
This package makes it easy to build and customize timeline UI.
---
**Checklist**
---
> Add Timelines

- source.md
Just added Italy community links (telegram and website)
---
**Checklist**
> Added italy's Flutter community links

- source.md
Added bitsdojo_window - https://github.com/bitsdojo/bitsdojo_window
---
**Checklist**
---
</a>
``` 
</a>
```
> Added bitsdojo_window

- source.md
Just fixing a profile link @Solido
> Fixing profile link

- source.md
Added a new category: 'Interviews'. In addition, added its new articles (part 1, 2, & 3).
---
**Checklist**
---
</a>
``` 
</a>
```
> Add new category & its contents

- source.md
Flutter library which helps to develop an iOS14 Widgets Extension. Using this plugin you can communicate with the widget and trigger an update. 🍏📱
Plugin: https://github.com/fasky-software/flutter_widgetkit
Blog: https://thomas-leiter.medium.com/develop-an-ios-14-widget-in-flutter-with-swiftui-e98eaff2c606
---
**Checklist**
> added WidgetKit Plugin to the device plugin section

- source.md
Add binder in the state management section
---
**Checklist**
---
</a>
``` 
</a>
```
> Add binder to state management section

- source.md
Triggered by https://twitter.com/BlueAquilae/status/1334578557524336647?s=20.
Funvas is interesting because it allows creating fun time based canvas animations, as can be seen in the [repo README](https://github.com/creativecreatorormaybenot/funvas).
---
**Checklist**
> Add funvas as an animation framework

- contributing.md
Simple typo fix, from détails to details in contributing.md
> Fix typo on contributing.md

- source.md
Solving the responsiveness challenge in a better way IMHO. A framework for adapting apps to different screen sizes. 
https://github.com/Codelessly/ResponsiveFramework
> Responsive Framework

- source.md
flutter-pi: A light-weight Flutter Engine Embedder for Raspberry Pi
---
**Checklist**
---
</a>
``` 
</a>
```
> Raspberry Pi Embedder

- source.md
[WeChat Assets Picker](https://github.com/fluttercandies/flutter_wechat_assets_picker) is an assets picker in WeChat style, support multi assets picking.
[WeChat Camera Picker](https://github.com/fluttercandies/flutter_wechat_camera_picker) is an extension for wechat_assets_picker, also in WeChat style.
These pickers covered image picking and camera shooting requests and the whole project looks exactly the same as WeChat. They also support custom theme/texts/filter and multiple options were provided. The most important is those library are in pure flutter but have high performance (include HEIF support). The author for multi_image_picker also gives a positive comment to those pickers, and we've talked about our packages in emails. I've wrote an …
> Add WeChat assets/camera picker

- source.md
Adding Cameroon Flutter community infos
[https://github.com/llastkrakw/awesome-flutter](url)
**Checklist**
---
</a>
``` 
</a>
```
> Add Cameroon Flutter community

- source.md
#384  Description
[timeline_tile](https://github.com/JHBitencourt/timeline_tile) is a package that helps to build custom timelines. The [beautiful_timelines](https://github.com/JHBitencourt/beautiful_timelines) repository showcases some real world timelines built with the package. 
---
**Checklist**
> Add timeline_tile package and beautiful_timelines repository

- source.md
Add a link to [this package](https://github.com/roipeker/graphx) by @roipeker under "experimental".
---
**Checklist**
> Add graphX

- source.md
A widget to show tasks on customizable calendar
> Add Time Planner

- source.md
Last try for adding this awesome package; I'll close this PR within a week, i hates pending PR which means this package doesn't deserve to list here.
https://pub.dev/packages/google_nav_bar
> Add GoogleNavBar

- source.md
Addition of the Code Field package
https://github.com/BertrandBev/code_field
Live demo
https://bertrandbev.github.io/code_field/#/
> Add CodeField package

- source.md
> Update the twitter link of one of the tutorials developer

- source.md
Fast i18n (https://github.com/Tienisto/flutter-fast-i18n) is an i18n library taking advantage of code generation to minimize bloat and provide a high degree of type safety.
I wanted to bring code generation to the next level. You can remove this library after code generation. The generated file works without any dependencies.
Furthermore, the I18n solution is very autocompletion-friendly: you can autocomplete translation keys, autocomplete parameters, you can even autocomplete one of the supported languages because it also generates a custom locale enum for your project.
Unlike `gen_lang`, this library is still active.
---
**Checklist**
> Add fast_i18n

- README.md
- source.md
Added Flutter Sidekick app to utilities section
---
**Checklist**
> Flutter sidekick

- source.md
This PR adds the Kenyan community meetup and twitter links.
---
**Checklist**
- [x ] I read [How to contribute](https://github.com/Solido/awesome-flutter/blob/master/contributing.md)
- [x ] I edited the SOURCE.md file only
---
</a>
``` 
</a>
```
> Add Kenyan Flutter community

- source.md
[Space-Empires](https://www.github.com/satyamx64/space_empires) is a turn-based strategy game of 4X (abbreviation of Explore, Expand, Exploit, Exterminate) subgenre complemented with Decent UI and smooth animations. There are 8 Planets, and 4 Players ( 1 User + 3 Computer A.I). The objective is to win them all in under 365 turns. To do so, the player must manage their resources, make military, and win the war against other races. 
**Checklist**
> Add Space Empires

- source.md
Added beamer package ([pub](https://pub.dev/packages/beamer), [GitHub](https://github.com/slovnicki/beamer)) to _Navigation_ section. This package eases the use of Navigator 2.0 API and also enables browser sync by default.
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Beamer package to Navigation section

- source.md
I tried to only add articles that were appropriate for this page, but feel free to reject or recategorize any of my additions. All of my Medium links are friend links so no one should be pay-walled.
Additional notes/suggestions:
- Combine the Tutorial and Howtos sections. These are basically synonyms.
- There are quite a few more really good YouTube channels that could be added. I've seen a list somewhere on Twitter but I don't know where it is now.
- There are a couple more active English podcasts. (Flying High with Flutter and Flutter 101)
- Some of the current links seem old or in the wrong category.
---
**Checklist**
---
Feel free to add this badge to …
> Articles from Suragch

- source.md
Add [RoundedLoadingButton](https://pub.dev/packages/rounded_loading_button) - Button with a loading indicator, complete with success and error animations
---
**Checklist**
> Add RoundedLoadingButton

- source.md
Add [NETCoreSync](https://github.com/aldycool/NETCoreSync) - Centralized database synchronization framework for multiple clients built on top of [Moor](https://github.com/simolus3/moor) library
---
**Checklist**
> Add NETCoreSync

- source.md
It's a PlutoGrid which is a DataGrid. It is about to be added to UI components.
---
**Checklist**
---
</a>
``` 
</a>
```
> Add PlutoGrid package in UI section.

- source.md
Hi, I'm making a PR as you proposed in https://github.com/joanpablo/reactive_forms/issues/227
I created a new section `Froms` to distinguish form engines from other types of packages.
**Checklist**
> reactive-forms added

- source.md
---
**Checklist**
---
</a>
``` 
</a>
```
> Add AppFlowy to the List

- source.md
Here is the repo:
https://github.com/ruskakimov/mooltik
Can be used as a reference for anyone trying to build an app related to drawing. 🙂
Source code of these features can be especially helpful to the community:
- Performant bucket fill
- Drawing on the canvas, canvas zoom and rotation
- Lasso transform tool
- Color picker
- Encoding images and sound into an MP4 with ffmpeg
---
**Checklist**
---
</a>
``` 
</a>
```
> Add Mooltik to Open Source Apps

- source.md
Backdrop [[git repo](https://github.com/fluttercommunity/backdrop),[pub package](https://pub.dev/packages/backdrop),[live demo](https://fluttercommunity.github.io/backdrop/demo/#/)] is a flutter implementation of [Backdrop component as per Material Design Guidelines](https://material.io/components/backdrop). The widget covers all use-cases and guidelines provided in MDG.
---
**Checklist**
---
</a>
``` 
</a>
```
> add Backdrop to `UI/Material Design`

- README.md
- source.md
Adding a link to my article about flutter shaders: https://wolfenrain.medium.com/flutter-shaders-an-initial-look-d9eb98d3fd7a.
I dont think the article itself is advanced but shaders can be considered difficult for some to grasp especially in combination with Flutter as it requires some knowledge about the underlaying canvas. But I am okay with moving it to any other category of your choosing.
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Flutter & Shaders article

- source.md
Adds map package to the list.
Repo: https://github.com/xclud/flutter_map
Pub.dev: https://pub.dev/packages/map
Web demo: https://xclud.github.io/flutter_map
---
**Checklist**
---
</a>
``` 
</a>
```
> Add map package to the list (https://pub.dev/packages/map)

- source.md
[Advance Image Picker](https://pub.dev/packages/advance_image_picker) - Flutter plugin in pure Dart code for selecting/editing multiple images from the Android/iOS image library and taking new pictures with the camera in the same view, by [WetaVN](https://github.com/weta-vn)
- Display live camera preview in a widget
- Adjust exposure
- Zoom camera preview
- Capture photo without saving into device library
- Capture with preview size mode & full screen size mode
- Select photos from device library by browsing photo albums
- Preview selected images
- Support button label & text translation
- Easy image editing features, such as rotation, cropping, adding sticker/filters
- Allow user add external image editors for editing selected images.
> Add Advance Image Picker plugin to Image Picker section

- source.md
Repo: https://github.com/KRTirtho/spotube
Binaries: https://github.com/KRTirtho/spotube/releases/tag/v2.0.0
Spotube is a lightweight Spotify client for both mobile (Android) & desktop (Mac, Windows & Linux). It utilizes the power of Spotify & Youtube's public API & creates a hazardless, performant & resource friendly User Experience
**Application Screenshots:**
**Desktop**
**Mobile**
---
**Checklist**
---
</a>
``` 
</a>
```
Definitely gonna add this awesome badge of honor once the PR gets merged
> Add Spotube in Top Open Source Apps category

- source.md
Repo: https://github.com/RafaelBarbosatec/bonfire
Examples: https://bonfire-engine.github.io/#/examples
Flame engine based game engine for 2D RPG games
---
**Checklist**
---
</a>
``` 
</a>
```
> Add bonfire game engine

- source.md
Zerker is a flexible and lightweight flutter canvas graphic animation library.
With Zerker, you can create a lot of seemingly cumbersome animation effects, such as animated animations, pop-up animations, scene transitions, icon effects, and more.
At the same time, you can create a lot of simple games with Zerker. Zerker contains elements such as sprites, scrolling backgrounds, and atlases, making it easy to create game worlds with them.
[https://github.com/flutterkit/zerker](https://github.com/flutterkit/zerker)
---
**Checklist**
---
<a …
> Add Zerker

- README.md
- source.md
Hi @Solido! I'm suggesting adding [Patrol](https://patrol.leancode.co/) – a new testing framework we've been working on at LeanCode for the last few months. Recently we went open-source. We're still in beta but we've received [very](https://twitter.com/LeanCodePl/status/1572507574070837250) [nice](https://github.com/leancodepl/patrol/discussions/348) reception from the community :)
**Checklist**
> Add Patrol – a new, powerful Flutter-first UI testing framework

- source.md
Added the [Flutter Chat UI](https://github.com/flyerhq/flutter_chat_ui) library. Helps as a fast quick start when making chat apps with Flutter
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Flutter Chat UI

- source.md
Fix link of device_calendar
---
**Checklist**
---
</a>
``` 
</a>
```
> Fix device_calendar link

- source.md
Add the link to the Flutter Nantes meetup : https://www.meetup.com/fr-FR/flutter-nantes/
---
**Checklist**
---
</a>
``` 
</a>
```
> Add Flutter Nantes meetup

- source.md
https://www.meetup.com/flutter-voronezh/
---
**Checklist**
---
</a>
``` 
</a>
```
> Add Flutter meetup Voronezh Russia

- source.md
Channel Oh, my Flutter in Russian, everything about Flutter - https://t.me/ohmyflutter
---
**Checklist**
---
</a>
``` 
</a>
```
> Add 'Oh, my Flutter' channel in Russian

- source.md
Add [Spotube](https://github.com/KRTirtho/spotube) to `Open Source Apps` > `Premium`. It has 20 652 starts as of today.
I put it in Premium because it's a complex application with many features.
---
**Checklist**
---
</a>
``` 
</a>
```
> feat(Open Source Apps): add Spotube

- source.md
[Flutter Plugins](https://github.com/flutter/plugins) are deprecated since Feb 22, 2023.
Projects were moved to [Flutter Packages](https://github.com/flutter/packages/)
All I did was fixing existing links from the deprecated version to the active stable version.
---
**Checklist**
---
</a>
``` 
</a>
```
> Fixed deprecated links

- source.md
PR to add Openreads Flutter app.
Link to repo: [https://github.com/mateusz-bak/openreads-android](https://github.com/mateusz-bak/openreads-android)
Openreads is a simple privacy oriented mobile books tracker using Open Library API.
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Openreads app

- source.md
Added [auto_route](https://pub.dev/packages/auto_route) library to the navigation section.
auto_route has a fair amount of active users and good enough likes on pub.dev
---
**Checklist**
---
</a>
``` 
</a>
```
> Add auto_route to navigation section

- source.md
Added [Video Editor](https://github.com/LeGoffMael/video_editor) library. A flutter package for editing video written in pure Dart with fully customizable UI. Supports crop, trim, rotation and cover selection.
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Video Editor

- source.md
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Flutter Animate

- source.md
With [Live activities](https://github.com/istornz/live_activities) you can use iOS 16.1+ Live Activities & iPhone 14 Pro+ Dynamic Island features.
Example:
---
**Checklist**
---
</a>
``` 
</a>
```
> Add Live Activities

- source.md
Repo: https://github.com/JideGuru/flutter_drawing_board
> Let's Draw is a simple drawing app where users can use freehand, line, and shape tools to draw art on the canvas. The demo is available at https://letsdraw.jideguru.dev/#/
---
**Checklist**
---
</a>
``` 
</a>
```
> Added Let's Draw

- source.md
Repo: https://github.com/britannio/in_app_review
> A Flutter plugin that lets you show a review pop up where users can leave a review for your app without needing to close your app. Alternatively, you can open your store listing via a deep link.
> It uses the [In-App Review](https://developer.android.com/guide/playcore/in-app-review) API on Android and the [SKStoreReviewController](https://developer.apple.com/documentation/storekit/skstorereviewcontroller) on iOS/MacOS.
Also minor clean-ups (Fix App Review).
---
**Checklist**
---
</a>
``` 
</a>
```
> Add In App Review

- source.md
Hi. I just added the [Flutter4Fun](http://flutter4fun.com/) blog in the `Websites / Blogs` section.
> Add Flutter4Fun blog in Websites / Blogs section

- source.md
Forui is a UI library that provides a set of minimalistic widgets heavily inspired by [shadcn/ui](https://ui.shadcn.com/).
For some context, these are the newest widgets we've added in our latest release.
https://github.com/user-attachments/assets/37a4b7b6-7941-42a2-9715-e6ae2dfed398
In addition, I noticed a broken link for `Flutter Bounty Hunters` and fixed it.
Submission description/links here
**GitHub:** https://github.com/forus-labs/forui
**Pub.dev:** https://pub.dev/packages/forui
**Website:** https://forui.dev/
---
**Checklist**
---
<a …
> Add forui ui library

- source.md
I really enjoyed using this project, nice work! Caught a couple of typos in the README though 😛
Submission description/links here
---
**Checklist**
---
</a>
``` 
</a>
```
> Update source.md, fix typos

- source.md
Adding [Nitric](https://nitric.io), an open source universal (multi-language and multi-cloud) backend framework, with concise infrastructure and pluggable deployment automation.
Dart SDK: https://github.com/nitrictech/dart-sdk
pubdev: https://pub.dev/packages/nitric_sdk
Main repo: https://github.com/nitrictech/nitric
---
**Checklist**
---
</a>
``` 
</a>
```
> add nitric to backend category

- source.md
https://github.com/HemantKArya/BloomeeTunes
---
**Checklist**
---
</a>
``` 
</a>
```
> Add BloomeeTunes 🌸
